import { ICountry } from '@/types/autocomplete'

export default [
  {
    country_rus: 'Австралия',
    country_eng: 'Australia',
    code: 'AU',
    phone_code: 61,
    phone_mask: '(999) 999-999',
    emoji: '🇦🇺',
    unicode: 'U+1F1E6 U+1F1FA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg',
    country_uzb: 'Avstraliya',
  },
  {
    country_rus: 'Австрия',
    country_eng: 'Austria',
    code: 'AT',
    phone_code: 43,
    phone_mask: '(999) 999999',
    emoji: '🇦🇹',
    unicode: 'U+1F1E6 U+1F1F9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AT.svg',
    country_uzb: 'Avstriya',
  },
  {
    country_rus: 'Азербайджан',
    country_eng: 'Azerbaijan',
    code: 'AZ',
    phone_code: 994,
    phone_mask: '(99) 999-99-99',
    emoji: '🇦🇿',
    unicode: 'U+1F1E6 U+1F1FF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AZ.svg',
    country_uzb: 'Ozarbayjon',
  },
  {
    country_rus: 'Албания',
    country_eng: 'Albania',
    code: 'AL',
    phone_code: 355,
    phone_mask: '(99) 999-9999',
    emoji: '🇦🇱',
    unicode: 'U+1F1E6 U+1F1F1',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AL.svg',
    country_uzb: 'Albaniya',
  },
  {
    country_rus: 'Алжир',
    country_eng: 'Algeria',
    code: 'DZ',
    phone_code: 21,
    phone_mask: '(999) 99-99-99',
    emoji: '🇩🇿',
    unicode: 'U+1F1E9 U+1F1FF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DZ.svg',
    country_uzb: 'Jazoir',
  },
  {
    country_rus: 'Американские Виргинские острова',
    country_eng: 'US Virgin Islands',
    code: 'VI',
    phone_code: 1340,
    phone_mask: '(999) 999-9999',
    emoji: '🇻🇮',
    unicode: 'U+1F1FB U+1F1EE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VI.svg',
    country_uzb: 'Amerika Virjiniya orollari',
  },
  {
    country_rus: 'Американское Самоа',
    country_eng: 'American Samoa',
    code: 'AS',
    phone_code: 684,
    phone_mask: '(999) 999-9999',
    emoji: '🇦🇸',
    unicode: 'U+1F1E6 U+1F1F8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AS.svg',
    country_uzb: 'Amerika Samoasi',
  },
  {
    country_rus: 'Ангилья',
    country_eng: 'Anguilla',
    code: 'AI',
    phone_code: 1264,
    phone_mask: '(999) 999-9999',
    emoji: '🇦🇮',
    unicode: 'U+1F1E6 U+1F1EE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AI.svg',
    country_uzb: 'Angilya',
  },
  {
    country_rus: 'Ангола',
    country_eng: 'Angola',
    code: 'AO',
    phone_code: 244,
    phone_mask: '(999) 999-999',
    emoji: '🇦🇴',
    unicode: 'U+1F1E6 U+1F1F4',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AO.svg',
    country_uzb: 'Angola',
  },
  {
    country_rus: 'Андорра',
    country_eng: 'Andorra',
    code: 'AD',
    phone_code: 376,
    phone_mask: '(999) 999',
    emoji: '🇦🇩',
    unicode: 'U+1F1E6 U+1F1E9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AD.svg',
    country_uzb: 'Andorra',
  },
  {
    country_rus: 'Антигуа и Барбуда',
    country_eng: 'Antigua And Barbuda',
    code: 'AG',
    phone_code: 1268,
    phone_mask: '(999) 999-9999',
    emoji: '🇦🇬',
    unicode: 'U+1F1E6 U+1F1EC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AG.svg',
    country_uzb: 'Antigua va Barbuda',
  },
  {
    country_rus: 'Аргентина',
    country_eng: 'Argentina',
    code: 'AR',
    phone_code: 54,
    phone_mask: '(9) 99-9999-9999',
    emoji: '🇦🇷',
    unicode: 'U+1F1E6 U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AR.svg',
    country_uzb: 'Argentina',
  },
  {
    country_rus: 'Армения',
    country_eng: 'Armenia',
    code: 'AM',
    phone_code: 374,
    phone_mask: '(99) 999999',
    emoji: '🇦🇲',
    unicode: 'U+1F1E6 U+1F1F2',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AM.svg',
    country_uzb: 'Armaniston',
  },
  {
    country_rus: 'Аруба',
    country_eng: 'Aruba',
    code: 'AW',
    phone_code: 297,
    phone_mask: '(999) 9999',
    emoji: '🇦🇼',
    unicode: 'U+1F1E6 U+1F1FC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AW.svg',
    country_uzb: 'Aruba',
  },
  {
    country_rus: 'Афганистан',
    country_eng: 'Afghanistan',
    code: 'AF',
    phone_code: 93,
    phone_mask: '(99) 999-9999',
    emoji: '🇦🇫',
    unicode: 'U+1F1E6 U+1F1EB',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg',
    country_uzb: 'Afgʻoniston',
  },
  {
    country_rus: 'Багамские острова',
    country_eng: 'Bahamas',
    code: 'BS',
    phone_code: 1242,
    phone_mask: '(999) 999-9999',
    emoji: '🇧🇸',
    unicode: 'U+1F1E7 U+1F1F8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BS.svg',
    country_uzb: 'Bagama orollari',
  },
  {
    country_rus: 'Бангладеш',
    country_eng: 'Bangladesh',
    code: 'BD',
    phone_code: 880,
    phone_mask: '(9999) 999999',
    emoji: '🇧🇩',
    unicode: 'U+1F1E7 U+1F1E9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BD.svg',
    country_uzb: 'Bangladesh',
  },
  {
    country_rus: 'Барбадос',
    country_eng: 'Barbados',
    code: 'BB',
    phone_code: 1246,
    phone_mask: '(999) 999-9999',
    emoji: '🇧🇧',
    unicode: 'U+1F1E7 U+1F1E7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BB.svg',
    country_uzb: 'Barbados',
  },
  {
    country_rus: 'Бахрейн',
    country_eng: 'Bahrain',
    code: 'BH',
    phone_code: 973,
    phone_mask: '(9999) 999999',
    emoji: '🇧🇭',
    unicode: 'U+1F1E7 U+1F1ED',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BH.svg',
    country_uzb: 'Bahrayn',
  },
  {
    country_rus: 'Беларусь',
    country_eng: 'Belarus',
    code: 'BY',
    phone_code: 375,
    phone_mask: '(99) 999-99-99',
    emoji: '🇧🇾',
    unicode: 'U+1F1E7 U+1F1FE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg',
    country_uzb: 'Belarus',
  },
  {
    country_rus: 'Белиз',
    country_eng: 'Belize',
    code: 'BZ',
    phone_code: 501,
    phone_mask: '(999) 9999',
    emoji: '🇧🇿',
    unicode: 'U+1F1E7 U+1F1FF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BZ.svg',
    country_uzb: 'Beliz',
  },
  {
    country_rus: 'Бельгия',
    country_eng: 'Belgium',
    code: 'BE',
    phone_code: 32,
    phone_mask: '(999) 99-99-99',
    emoji: '🇧🇪',
    unicode: 'U+1F1E7 U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BE.svg',
    country_uzb: 'Belgiya',
  },
  {
    country_rus: 'Бенин',
    country_eng: 'Benin',
    code: 'BJ',
    phone_code: 229,
    phone_mask: '(99) 99-99-99',
    emoji: '🇧🇯',
    unicode: 'U+1F1E7 U+1F1EF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BJ.svg',
    country_uzb: 'Benin',
  },
  {
    country_rus: 'Бермудские острова',
    country_eng: 'Bermuda',
    code: 'BM',
    phone_code: 1441,
    phone_mask: '(999) 999-9999',
    emoji: '🇧🇲',
    unicode: 'U+1F1E7 U+1F1F2',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BM.svg',
    country_uzb: 'Bermuda orollari',
  },
  {
    country_rus: 'Болгария',
    country_eng: 'Bulgaria',
    code: 'BG',
    phone_code: 359,
    phone_mask: '(99) 999-999',
    emoji: '🇧🇬',
    unicode: 'U+1F1E7 U+1F1EC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BG.svg',
    country_uzb: 'Bolgariya',
  },
  {
    country_rus: 'Боливия',
    country_eng: 'Bolivia',
    code: 'BO',
    phone_code: 591,
    phone_mask: '99999999',
    emoji: '🇧🇴',
    unicode: 'U+1F1E7 U+1F1F4',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BO.svg',
    country_uzb: 'Boliviya',
  },
  {
    country_rus: 'Босния и Герцеговина',
    country_eng: 'Bosnia And Herzegovina',
    code: 'BA',
    phone_code: 387,
    phone_mask: '(99) 999-999',
    emoji: '🇧🇦',
    unicode: 'U+1F1E7 U+1F1E6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BA.svg',
    country_uzb: 'Bosniya va Gertsegovina',
  },
  {
    country_rus: 'Ботсвана',
    country_eng: 'Botswana',
    code: 'BW',
    phone_code: 267,
    phone_mask: '(99) 999-999',
    emoji: '🇧🇼',
    unicode: 'U+1F1E7 U+1F1FC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BW.svg',
    country_uzb: 'Botsvana',
  },
  {
    country_rus: 'Бразилия',
    country_eng: 'Brazil',
    code: 'BR',
    phone_code: 55,
    phone_mask: '(99) 99999-9999',
    emoji: '🇧🇷',
    unicode: 'U+1F1E7 U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg',
    country_uzb: 'Braziliya',
  },
  {
    country_rus: 'Бруней-Даруссалам',
    country_eng: 'Brunei Darussalam',
    code: 'BN',
    phone_code: 673,
    phone_mask: '(999) 9999',
    emoji: '🇧🇳',
    unicode: 'U+1F1E7 U+1F1F3',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BN.svg',
    country_uzb: 'Bruney-Darusalam',
  },
  {
    country_rus: 'Буркина-Фасо',
    country_eng: 'Burkina Faso',
    code: 'BF',
    phone_code: 226,
    phone_mask: '(99) 99-99-99',
    emoji: '🇧🇫',
    unicode: 'U+1F1E7 U+1F1EB',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BF.svg',
    country_uzb: 'Burkina Faso',
  },
  {
    country_rus: 'Бурунди',
    country_eng: 'Burundi',
    code: 'BI',
    phone_code: 257,
    phone_mask: '(99) 99-99-99',
    emoji: '🇧🇮',
    unicode: 'U+1F1E7 U+1F1EE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BI.svg',
    country_uzb: 'Burundi',
  },
  {
    country_rus: 'Бутан',
    country_eng: 'Bhutan',
    code: 'BT',
    phone_code: 975,
    phone_mask: '(99) 99-99-99',
    emoji: '🇧🇹',
    unicode: 'U+1F1E7 U+1F1F9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BT.svg',
    country_uzb: 'Butan',
  },
  {
    country_rus: 'Вануату',
    country_eng: 'Vanuatu',
    code: 'VU',
    phone_code: 678,
    phone_mask: '(999) 9999',
    emoji: '🇻🇺',
    unicode: 'U+1F1FB U+1F1FA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VU.svg',
    country_uzb: 'Vanuatu',
  },
  {
    country_rus: 'Великобритания',
    country_eng: 'United Kingdom',
    code: 'GB',
    phone_code: 44,
    phone_mask: '(9999) 999999',
    emoji: '🇬🇧',
    unicode: 'U+1F1EC U+1F1E7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg',
    country_uzb: 'Buyuk Britaniya',
  },
  {
    country_rus: 'Венгрия',
    country_eng: 'Hungary',
    code: 'HU',
    phone_code: 36,
    phone_mask: '(99) 999-9999',
    emoji: '🇭🇺',
    unicode: 'U+1F1ED U+1F1FA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HU.svg',
    country_uzb: 'Vengriya',
  },
  {
    country_rus: 'Венесуэла',
    country_eng: 'Venezuela',
    code: 'VE',
    phone_code: 58,
    phone_mask: '(999) 9999999',
    emoji: '🇻🇪',
    unicode: 'U+1F1FB U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg',
    country_uzb: 'Venesuela',
  },
  {
    country_rus: 'Вьетнам',
    country_eng: 'Vietnam',
    code: 'VN',
    phone_code: 84,
    phone_mask: '(99) 999-99-99',
    emoji: '🇻🇳',
    unicode: 'U+1F1FB U+1F1F3',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg',
    country_uzb: 'Vyetnam',
  },
  {
    country_rus: 'Габон',
    country_eng: 'Gabon',
    code: 'GA',
    phone_code: 241,
    phone_mask: '(9) 99-99-99',
    emoji: '🇬🇦',
    unicode: 'U+1F1EC U+1F1E6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GA.svg',
    country_uzb: 'Gabon',
  },
  {
    country_rus: 'Гаити',
    country_eng: 'Haiti',
    code: 'HT',
    phone_code: 509,
    phone_mask: '(99) 99-9999',
    emoji: '🇭🇹',
    unicode: 'U+1F1ED U+1F1F9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HT.svg',
    country_uzb: 'Gaiti',
  },
  {
    country_rus: 'Гайана',
    country_eng: 'Guyana',
    code: 'GY',
    phone_code: 592,
    phone_mask: '(999) 9999',
    emoji: '🇬🇾',
    unicode: 'U+1F1EC U+1F1FE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GY.svg',
    country_uzb: 'Gayana',
  },
  {
    country_rus: 'Гамбия',
    country_eng: 'Gambia',
    code: 'GM',
    phone_code: 220,
    phone_mask: '(999) 9999',
    emoji: '🇬🇲',
    unicode: 'U+1F1EC U+1F1F2',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GM.svg',
    country_uzb: 'Gambiya',
  },
  {
    country_rus: 'Гана',
    country_eng: 'Ghana',
    code: 'GH',
    phone_code: 233,
    phone_mask: '(99) 999-9999',
    emoji: '🇬🇭',
    unicode: 'U+1F1EC U+1F1ED',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GH.svg',
    country_uzb: 'Gana',
  },
  {
    country_rus: 'Гватемала',
    country_eng: 'Guatemala',
    code: 'GT',
    phone_code: 502,
    phone_mask: '(9999) 9999',
    emoji: '🇬🇹',
    unicode: 'U+1F1EC U+1F1F9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GT.svg',
    country_uzb: 'Gvatemala',
  },
  {
    country_rus: 'Гвинея',
    country_eng: 'Guinea',
    code: 'GN',
    phone_code: 224,
    phone_mask: '(999) 99-99-99',
    emoji: '🇬🇳',
    unicode: 'U+1F1EC U+1F1F3',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GN.svg',
    country_uzb: 'Gvineya',
  },
  {
    country_rus: 'Гвинея-Бисау',
    country_eng: 'Guinea-Bissau',
    code: 'GW',
    phone_code: 245,
    phone_mask: '(999) 999-999',
    emoji: '🇬🇼',
    unicode: 'U+1F1EC U+1F1FC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GW.svg',
    country_uzb: 'Gvineya-Bisau',
  },
  {
    country_rus: 'Германия',
    country_eng: 'Germany',
    code: 'DE',
    phone_code: 49,
    phone_mask: '(9999) 9999999',
    emoji: '🇩🇪',
    unicode: 'U+1F1E9 U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg',
    country_uzb: 'Germaniya',
  },
  {
    country_rus: 'Гибралтар',
    country_eng: 'Gibraltar',
    code: 'GI',
    phone_code: 350,
    phone_mask: '99999999',
    emoji: '🇬🇮',
    unicode: 'U+1F1EC U+1F1EE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GI.svg',
    country_uzb: 'Gibraltar',
  },
  {
    country_rus: 'Гондурас',
    country_eng: 'Honduras',
    code: 'HN',
    phone_code: 504,
    phone_mask: '(9999) 9999',
    emoji: '🇭🇳',
    unicode: 'U+1F1ED U+1F1F3',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HN.svg',
    country_uzb: 'Gonduras',
  },
  {
    country_rus: 'Гонконг',
    country_eng: 'Hong Kong',
    code: 'HK',
    phone_code: 852,
    phone_mask: '(9999) 9999',
    emoji: '🇭🇰',
    unicode: 'U+1F1ED U+1F1F0',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HK.svg',
    country_uzb: 'Gonkong',
  },
  {
    country_rus: 'Гренада',
    country_eng: 'Grenada',
    code: 'GD',
    phone_code: 1473,
    phone_mask: '(999) 999-9999',
    emoji: '🇬🇩',
    unicode: 'U+1F1EC U+1F1E9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GD.svg',
    country_uzb: 'Grenada',
  },
  {
    country_rus: 'Гренландия',
    country_eng: 'Greenland',
    code: 'GL',
    phone_code: 299,
    phone_mask: '(99) 99-99',
    emoji: '🇬🇱',
    unicode: 'U+1F1EC U+1F1F1',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GL.svg',
    country_uzb: 'Grenlandiya',
  },
  {
    country_rus: 'Греция',
    country_eng: 'Greece',
    code: 'GR',
    phone_code: 30,
    phone_mask: '(999) 999-9999',
    emoji: '🇬🇷',
    unicode: 'U+1F1EC U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GR.svg',
    country_uzb: 'Gretsiya',
  },
  {
    country_rus: 'Грузия',
    country_eng: 'Georgia',
    code: 'GE',
    phone_code: 995,
    phone_mask: '(999) 99-99-99',
    emoji: '🇬🇪',
    unicode: 'U+1F1EC U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GE.svg',
    country_uzb: 'Gruziya',
  },
  {
    country_rus: 'Гуам',
    country_eng: 'Guam (USA)',
    code: 'GU',
    phone_code: 671,
    phone_mask: '(999) 999-9999',
    emoji: '🇬🇺',
    unicode: 'U+1F1EC U+1F1FA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GU.svg',
    country_uzb: 'Guam',
  },
  {
    country_rus: 'Дания',
    country_eng: 'Denmark',
    code: 'DK',
    phone_code: 45,
    phone_mask: '(99) 99-99-99',
    emoji: '🇩🇰',
    unicode: 'U+1F1E9 U+1F1F0',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DK.svg',
    country_uzb: 'Daniya',
  },
  {
    country_rus: 'Джибути',
    country_eng: 'Djibouti',
    code: 'DJ',
    phone_code: 253,
    phone_mask: '(99) 99-99-99',
    emoji: '🇩🇯',
    unicode: 'U+1F1E9 U+1F1EF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DJ.svg',
    country_uzb: 'Jibuti',
  },
  {
    country_rus: 'Доминика',
    country_eng: 'Dominica',
    code: 'DM',
    phone_code: 1767,
    phone_mask: '(999) 999-9999',
    emoji: '🇩🇲',
    unicode: 'U+1F1E9 U+1F1F2',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DM.svg',
    country_uzb: 'Dominika',
  },
  {
    country_rus: 'Доминиканская Республика',
    country_eng: 'Dominican Republic',
    code: 'DO',
    phone_code: 1809,
    phone_mask: '(999) 999-9999',
    emoji: '🇩🇴',
    unicode: 'U+1F1E9 U+1F1F4',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DO.svg',
    country_uzb: 'Dominikan Respublikasi',
  },
  {
    country_rus: 'Египет',
    country_eng: 'Egypt',
    code: 'EG',
    phone_code: 20,
    phone_mask: '(999) 999-9999',
    emoji: '🇪🇬',
    unicode: 'U+1F1EA U+1F1EC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg',
    country_uzb: 'Misr',
  },
  {
    country_rus: 'Замбия',
    country_eng: 'Zambia',
    code: 'ZM',
    phone_code: 260,
    phone_mask: '(99) 9999999',
    emoji: '🇿🇲',
    unicode: 'U+1F1FF U+1F1F2',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZM.svg',
    country_uzb: 'Zambiya',
  },
  {
    country_rus: 'Западная Сахара',
    country_eng: 'Western Sahara',
    code: 'EH',
    phone_code: 21,
    phone_mask: '(999) 999999',
    emoji: '🇪🇭',
    unicode: 'U+1F1EA U+1F1ED',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EH.svg',
    country_uzb: "G'arbiy Sahroi",
  },
  {
    country_rus: 'Зимбабве',
    country_eng: 'Zimbabwe',
    code: 'ZW',
    phone_code: 263,
    phone_mask: '(99) 999-9999',
    emoji: '🇿🇼',
    unicode: 'U+1F1FF U+1F1FC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZW.svg',
    country_uzb: 'Zimbabve',
  },
  {
    country_rus: 'Израиль',
    country_eng: 'Israel',
    code: 'IL',
    phone_code: 972,
    phone_mask: '(99) 999-9999',
    emoji: '🇮🇱',
    unicode: 'U+1F1EE U+1F1F1',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IL.svg',
    country_uzb: 'Isroil',
  },
  {
    country_rus: 'Индия',
    country_eng: 'India',
    code: 'IN',
    phone_code: 91,
    phone_mask: '(99999) 99999',
    emoji: '🇮🇳',
    unicode: 'U+1F1EE U+1F1F3',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg',
    country_uzb: 'Hindiston',
  },
  {
    country_rus: 'Индонезия',
    country_eng: 'Indonesia',
    code: 'ID',
    phone_code: 62,
    phone_mask: '(999) 999-999',
    emoji: '🇮🇩',
    unicode: 'U+1F1EE U+1F1E9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg',
    country_uzb: 'Indoneziya',
  },
  {
    country_rus: 'Иордания',
    country_eng: 'Jordan',
    code: 'JO',
    phone_code: 962,
    phone_mask: '(9) 9999-9999',
    emoji: '🇯🇴',
    unicode: 'U+1F1EF U+1F1F4',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JO.svg',
    country_uzb: 'Iordaniya',
  },
  {
    country_rus: 'Ирак',
    country_eng: 'Iraq',
    code: 'IQ',
    phone_code: 964,
    phone_mask: '(999) 999-9999',
    emoji: '🇮🇶',
    unicode: 'U+1F1EE U+1F1F6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IQ.svg',
    country_uzb: 'Iroq',
  },
  {
    country_rus: 'Иран',
    country_eng: 'Iran',
    code: 'IR',
    phone_code: 98,
    phone_mask: '(999) 999-9999',
    emoji: '🇮🇷',
    unicode: 'U+1F1EE U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IR.svg',
    country_uzb: 'Eron',
  },
  {
    country_rus: 'Ирландия',
    country_eng: 'Ireland',
    code: 'IE',
    phone_code: 353,
    phone_mask: '(99) 999-9999',
    emoji: '🇮🇪',
    unicode: 'U+1F1EE U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg',
    country_uzb: 'Irlandiya',
  },
  {
    country_rus: 'Исландия',
    country_eng: 'Iceland',
    code: 'IS',
    phone_code: 354,
    phone_mask: '(999) 9999',
    emoji: '🇮🇸',
    unicode: 'U+1F1EE U+1F1F8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg',
    country_uzb: 'Islandiya',
  },
  {
    country_rus: 'Испания',
    country_eng: 'Spain',
    code: 'ES',
    phone_code: 34,
    phone_mask: '(999) 99-99-99',
    emoji: '🇪🇸',
    unicode: 'U+1F1EA U+1F1F8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg',
    country_uzb: 'Ispaniya',
  },
  {
    country_rus: 'Италия',
    country_eng: 'Italy',
    code: 'IT',
    phone_code: 39,
    phone_mask: '(999) 999-9999',
    emoji: '🇮🇹',
    unicode: 'U+1F1EE U+1F1F9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg',
    country_uzb: 'Italiya',
  },
  {
    country_rus: 'Йемен',
    country_eng: 'Yemen',
    code: 'YE',
    phone_code: 967,
    phone_mask: '(999) 999-999',
    emoji: '🇾🇪',
    unicode: 'U+1F1FE U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YE.svg',
    country_uzb: 'Yaman',
  },
  {
    country_rus: 'Кабо-Верде',
    country_eng: 'Cape Verde',
    code: 'CV',
    phone_code: 9,
    phone_mask: '(999) 99-99',
    emoji: '🇨🇻',
    unicode: 'U+1F1E8 U+1F1FB',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CV.svg',
    country_uzb: 'Kabo-Verde',
  },
  {
    country_rus: 'Казахстан',
    country_eng: 'Kazakhstan',
    code: 'KZ',
    phone_code: 7,
    phone_mask: '(999) 999-9999',
    emoji: '🇰🇿',
    unicode: 'U+1F1F0 U+1F1FF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KZ.svg',
    country_uzb: "Qozog'iston",
  },
  {
    country_rus: 'Камбоджа',
    country_eng: 'Cambodia',
    code: 'KH',
    phone_code: 855,
    phone_mask: '(99) 999-999',
    emoji: '🇰🇭',
    unicode: 'U+1F1F0 U+1F1ED',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KH.svg',
    country_uzb: 'Kambodja',
  },
  {
    country_rus: 'Камерун',
    country_eng: 'Cameroon',
    code: 'CM',
    phone_code: 237,
    phone_mask: '(9) 99-99-99-99',
    emoji: '🇨🇲',
    unicode: 'U+1F1E8 U+1F1F2',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CM.svg',
    country_uzb: 'Kamerun',
  },
  {
    country_rus: 'Канада',
    country_eng: 'Canada',
    code: 'CA',
    phone_code: 1,
    phone_mask: '(999) 999-9999',
    emoji: '🇨🇦',
    unicode: 'U+1F1E8 U+1F1E6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg',
    country_uzb: 'Kanada',
  },
  {
    country_rus: 'Катар',
    country_eng: 'Qatar',
    code: 'QA',
    phone_code: 974,
    phone_mask: '(9999) 9999',
    emoji: '🇶🇦',
    unicode: 'U+1F1F6 U+1F1E6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg',
    country_uzb: 'Qatar',
  },
  {
    country_rus: 'Кения',
    country_eng: 'Kenya',
    code: 'KE',
    phone_code: 254,
    phone_mask: '(999) 999999',
    emoji: '🇰🇪',
    unicode: 'U+1F1F0 U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KE.svg',
    country_uzb: 'Keniya',
  },
  {
    country_rus: 'Кипр',
    country_eng: 'Cyprus',
    code: 'CY',
    phone_code: 357,
    phone_mask: '(99) 999999',
    emoji: '🇨🇾',
    unicode: 'U+1F1E8 U+1F1FE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg',
    country_uzb: 'Kipr',
  },
  {
    country_rus: 'Кирибати',
    country_eng: 'Kiribati',
    code: 'KI',
    phone_code: 686,
    phone_mask: '99999999',
    emoji: '🇰🇮',
    unicode: 'U+1F1F0 U+1F1EE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KI.svg',
    country_uzb: 'Kiribati',
  },
  {
    country_rus: 'Китай',
    country_eng: 'China',
    code: 'CN',
    phone_code: 86,
    phone_mask: '(999) 9999-9999',
    emoji: '🇨🇳',
    unicode: 'U+1F1E8 U+1F1F3',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg',
    country_uzb: 'Xitoy',
  },
  {
    country_rus: 'Кокосовые острова',
    country_eng: 'Cocos (Keeling) Islands',
    code: 'CC',
    phone_code: 672,
    phone_mask: '(999) 999-999',
    emoji: '🇨🇨',
    unicode: 'U+1F1E8 U+1F1E8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CC.svg',
    country_uzb: 'Kokos orollari',
  },
  {
    country_rus: 'Колумбия',
    country_eng: 'Colombia',
    code: 'CO',
    phone_code: 57,
    phone_mask: '(999) 9999999',
    emoji: '🇨🇴',
    unicode: 'U+1F1E8 U+1F1F4',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg',
    country_uzb: 'Kolumbiya',
  },
  {
    country_rus: 'Коморские острова',
    country_eng: 'Comoros',
    code: 'KM',
    phone_code: 269,
    phone_mask: '(999) 99-99',
    emoji: '🇰🇲',
    unicode: 'U+1F1F0 U+1F1F2',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KM.svg',
    country_uzb: 'Komor orollari',
  },
  {
    country_rus: 'Конго',
    country_eng: 'Congo',
    code: 'CG',
    phone_code: 242,
    phone_mask: '99999999',
    emoji: '🇨🇬',
    unicode: 'U+1F1E8 U+1F1EC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CG.svg',
    country_uzb: 'Kongo',
  },
  {
    country_rus: 'Коста-Рика',
    country_eng: 'Costa Rica',
    code: 'CR',
    phone_code: 506,
    phone_mask: '(9999) 9999',
    emoji: '🇨🇷',
    unicode: 'U+1F1E8 U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CR.svg',
    country_uzb: 'Kosta-Rika',
  },
  {
    country_rus: "Кот д'Ивуар",
    country_eng: "Cote D'Ivoire",
    code: 'CI',
    phone_code: 225,
    phone_mask: '9999999',
    emoji: '🇨🇮',
    unicode: 'U+1F1E8 U+1F1EE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CI.svg',
    country_uzb: "Kot-d'Ivuar",
  },
  {
    country_rus: 'Куба',
    country_eng: 'Cuba',
    code: 'CU',
    phone_code: 53,
    phone_mask: '(9) 9999999',
    emoji: '🇨🇺',
    unicode: 'U+1F1E8 U+1F1FA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg',
    country_uzb: 'Kuba',
  },
  {
    country_rus: 'Кувейт',
    country_eng: 'Kuwait',
    code: 'KW',
    phone_code: 965,
    phone_mask: '(999) 99999',
    emoji: '🇰🇼',
    unicode: 'U+1F1F0 U+1F1FC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KW.svg',
    country_uzb: 'Quvayt',
  },
  {
    country_rus: 'Кыргызстан',
    country_eng: 'Kyrgyzstan',
    code: 'KG',
    phone_code: 996,
    phone_mask: '(999) 999-999',
    emoji: '🇰🇬',
    unicode: 'U+1F1F0 U+1F1EC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KG.svg',
    country_uzb: "Qirg'iziston",
  },
  {
    country_rus: 'Лаос',
    country_eng: 'Laos',
    code: 'LA',
    phone_code: 856,
    phone_mask: '(99) 99-999-999',
    emoji: '🇱🇦',
    unicode: 'U+1F1F1 U+1F1E6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg',
    country_uzb: 'Laos',
  },
  {
    country_rus: 'Латвия',
    country_eng: 'Latvia',
    code: 'LV',
    phone_code: 371,
    phone_mask: '(99) 999-999',
    emoji: '🇱🇻',
    unicode: 'U+1F1F1 U+1F1FB',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LV.svg',
    country_uzb: 'Latviya',
  },
  {
    country_rus: 'Лесото',
    country_eng: 'Lesotho',
    code: 'LS',
    phone_code: 266,
    phone_mask: '(9999) 9999',
    emoji: '🇱🇸',
    unicode: 'U+1F1F1 U+1F1F8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LS.svg',
    country_uzb: 'Lesoto',
  },
  {
    country_rus: 'Либерия',
    country_eng: 'Liberia',
    code: 'LR',
    phone_code: 231,
    phone_mask: '(99) 999-9999',
    emoji: '🇱🇷',
    unicode: 'U+1F1F1 U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LR.svg',
    country_uzb: 'Liberiya',
  },
  {
    country_rus: 'Ливан',
    country_eng: 'Lebanon',
    code: 'LB',
    phone_code: 961,
    phone_mask: '(99) 999-999',
    emoji: '🇱🇧',
    unicode: 'U+1F1F1 U+1F1E7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LB.svg',
    country_uzb: 'Livan',
  },
  {
    country_rus: 'Ливия',
    country_eng: 'Libya',
    code: 'LY',
    phone_code: 21,
    phone_mask: '(99) 9999999',
    emoji: '🇱🇾',
    unicode: 'U+1F1F1 U+1F1FE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LY.svg',
    country_uzb: 'Liviya',
  },
  {
    country_rus: 'Литва',
    country_eng: 'Lithuania',
    code: 'LT',
    phone_code: 370,
    phone_mask: '(999) 99999',
    emoji: '🇱🇹',
    unicode: 'U+1F1F1 U+1F1F9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LT.svg',
    country_uzb: 'Litva',
  },
  {
    country_rus: 'Люксембург',
    country_eng: 'Luxembourg',
    code: 'LU',
    phone_code: 352,
    phone_mask: '(999) 999-999',
    emoji: '🇱🇺',
    unicode: 'U+1F1F1 U+1F1FA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LU.svg',
    country_uzb: 'Lyuksemburg',
  },
  {
    country_rus: 'Маврикий',
    country_eng: 'Mauritius',
    code: 'MU',
    phone_code: 230,
    phone_mask: '(9999) 9999',
    emoji: '🇲🇺',
    unicode: 'U+1F1F2 U+1F1FA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MU.svg',
    country_uzb: 'Mavrikiy',
  },
  {
    country_rus: 'Мадагаскар',
    country_eng: 'Madagascar',
    code: 'MG',
    phone_code: 261,
    phone_mask: '(99) 99-999-99',
    emoji: '🇲🇬',
    unicode: 'U+1F1F2 U+1F1EC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MG.svg',
    country_uzb: 'Madagaskar',
  },
  {
    country_rus: 'Макао',
    country_eng: 'Macau',
    code: 'MO',
    phone_code: 853,
    phone_mask: '(9999) 9999',
    emoji: '🇲🇴',
    unicode: 'U+1F1F2 U+1F1F4',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MO.svg',
    country_uzb: 'Makao',
  },
  {
    country_rus: 'Македония',
    country_eng: 'Macedonia',
    code: 'MK',
    phone_code: 389,
    phone_mask: '(99) 999-999',
    emoji: '🇲🇰',
    unicode: 'U+1F1F2 U+1F1F0',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MK.svg',
    country_uzb: 'Makedoniya',
  },
  {
    country_rus: 'Малави',
    country_eng: 'Malawi',
    code: 'MW',
    phone_code: 265,
    phone_mask: '(999) 99-99-99',
    emoji: '🇲🇼',
    unicode: 'U+1F1F2 U+1F1FC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MW.svg',
    country_uzb: 'Malavi',
  },
  {
    country_rus: 'Малайзия',
    country_eng: 'Malaysia',
    code: 'MY',
    phone_code: 60,
    phone_mask: '(99) 999-9999',
    emoji: '🇲🇾',
    unicode: 'U+1F1F2 U+1F1FE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg',
    country_uzb: 'Malayziya',
  },
  {
    country_rus: 'Мали',
    country_eng: 'Mali',
    code: 'ML',
    phone_code: 223,
    phone_mask: '(99) 99-99-99',
    emoji: '🇲🇱',
    unicode: 'U+1F1F2 U+1F1F1',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ML.svg',
    country_uzb: 'Mali',
  },
  {
    country_rus: 'Мальдивы',
    country_eng: 'Maldives',
    code: 'MV',
    phone_code: 960,
    phone_mask: '(999) 9999',
    emoji: '🇲🇻',
    unicode: 'U+1F1F2 U+1F1FB',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MV.svg',
    country_uzb: 'Maldiv orollari',
  },
  {
    country_rus: 'Мальта',
    country_eng: 'Malta',
    code: 'MT',
    phone_code: 356,
    phone_mask: '(9999) 9999',
    emoji: '🇲🇹',
    unicode: 'U+1F1F2 U+1F1F9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MT.svg',
    country_uzb: 'Malta',
  },
  {
    country_rus: 'Марокко',
    country_eng: 'Morocco',
    code: 'MA',
    phone_code: 212,
    phone_mask: '(999) 999999',
    emoji: '🇲🇦',
    unicode: 'U+1F1F2 U+1F1E6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MA.svg',
    country_uzb: 'Marokash',
  },
  {
    country_rus: 'Мартиника',
    country_eng: 'Martinique',
    code: 'MQ',
    phone_code: 596,
    phone_mask: '(999) 99-99-99',
    emoji: '🇲🇶',
    unicode: 'U+1F1F2 U+1F1F6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MQ.svg',
    country_uzb: 'Martinika',
  },
  {
    country_rus: 'Маршалловы острова',
    country_eng: 'Marshall Islands',
    code: 'MH',
    phone_code: 692,
    phone_mask: '(999) 9999',
    emoji: '🇲🇭',
    unicode: 'U+1F1F2 U+1F1ED',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MH.svg',
    country_uzb: 'Marshall orollari',
  },
  {
    country_rus: 'Мексика',
    country_eng: 'Mexico',
    code: 'MX',
    phone_code: 52,
    phone_mask: '(9) 999-999-9999',
    emoji: '🇲🇽',
    unicode: 'U+1F1F2 U+1F1FD',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg',
    country_uzb: 'Meksika',
  },
  {
    country_rus: 'Микронезия',
    country_eng: 'Federated States of Micronesia',
    code: 'FM',
    phone_code: 691,
    phone_mask: '(999) 9999',
    emoji: '🇫🇲',
    unicode: 'U+1F1EB U+1F1F2',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FM.svg',
    country_uzb: 'Mikroneziya',
  },
  {
    country_rus: 'Мозамбик',
    country_eng: 'Mozambique',
    code: 'MZ',
    phone_code: 258,
    phone_mask: '(99) 999-9999',
    emoji: '🇲🇿',
    unicode: 'U+1F1F2 U+1F1FF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MZ.svg',
    country_uzb: 'Mozambik',
  },
  {
    country_rus: 'Молдова',
    country_eng: 'Moldova',
    code: 'MD',
    phone_code: 373,
    phone_mask: '(999) 99-999',
    emoji: '🇲🇩',
    unicode: 'U+1F1F2 U+1F1E9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MD.svg',
    country_uzb: 'Moldova',
  },
  {
    country_rus: 'Монако',
    country_eng: 'Monaco',
    code: 'MC',
    phone_code: 377,
    phone_mask: '(9) 99-99-99-99',
    emoji: '🇲🇨',
    unicode: 'U+1F1F2 U+1F1E8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MC.svg',
    country_uzb: 'Monako',
  },
  {
    country_rus: 'Монголия',
    country_eng: 'Mongolia',
    code: 'MN',
    phone_code: 976,
    phone_mask: '(9999) 9999',
    emoji: '🇲🇳',
    unicode: 'U+1F1F2 U+1F1F3',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg',
    country_uzb: 'Mongoliya',
  },
  {
    country_rus: 'Монсеррат',
    country_eng: 'Montserrat',
    code: 'MS',
    phone_code: 1664,
    phone_mask: '(999) 999-9999',
    emoji: '🇲🇸',
    unicode: 'U+1F1F2 U+1F1F8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MS.svg',
    country_uzb: 'Montserrat',
  },
  {
    country_rus: 'Мьянма',
    country_eng: 'Myanmar',
    code: 'MM',
    phone_code: 95,
    phone_mask: '(9) 999-9999',
    emoji: '🇲🇲',
    unicode: 'U+1F1F2 U+1F1F2',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MM.svg',
    country_uzb: 'Myanma',
  },
  {
    country_rus: 'Намибия',
    country_eng: 'Namibia',
    code: 'NA',
    phone_code: 264,
    phone_mask: '(99) 999-9999',
    emoji: '🇳🇦',
    unicode: 'U+1F1F3 U+1F1E6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NA.svg',
    country_uzb: 'Namibiya',
  },
  {
    country_rus: 'Науру',
    country_eng: 'Nauru',
    code: 'NR',
    phone_code: 674,
    phone_mask: '(999) 9999',
    emoji: '🇳🇷',
    unicode: 'U+1F1F3 U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NR.svg',
    country_uzb: 'Nauru',
  },
  {
    country_rus: 'Непал',
    country_eng: 'Nepal',
    code: 'NP',
    phone_code: 977,
    phone_mask: '(999) 9999999',
    emoji: '🇳🇵',
    unicode: 'U+1F1F3 U+1F1F5',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg',
    country_uzb: 'Nepal',
  },
  {
    country_rus: 'Нигер',
    country_eng: 'Niger',
    code: 'NE',
    phone_code: 227,
    phone_mask: '(99) 99-99-99',
    emoji: '🇳🇪',
    unicode: 'U+1F1F3 U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NE.svg',
    country_uzb: 'Niger',
  },
  {
    country_rus: 'Нигерия',
    country_eng: 'Nigeria',
    code: 'NG',
    phone_code: 234,
    phone_mask: '(999) 999-9999',
    emoji: '🇳🇬',
    unicode: 'U+1F1F3 U+1F1EC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg',
    country_uzb: 'Nigeriya',
  },
  {
    country_rus: 'Нидерланды',
    country_eng: 'Netherlands',
    code: 'NL',
    phone_code: 31,
    phone_mask: '(9) 99999999',
    emoji: '🇳🇱',
    unicode: 'U+1F1F3 U+1F1F1',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg',
    country_uzb: 'Niderlandlar',
  },
  {
    country_rus: 'Никарагуа',
    country_eng: 'Nicaragua',
    code: 'NI',
    phone_code: 505,
    phone_mask: '(9999) 9999',
    emoji: '🇳🇮',
    unicode: 'U+1F1F3 U+1F1EE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg',
    country_uzb: 'Nikaragua',
  },
  {
    country_rus: 'Ниуэ',
    country_eng: 'Niue',
    code: 'NU',
    phone_code: 683,
    phone_mask: '9999',
    emoji: '🇳🇺',
    unicode: 'U+1F1F3 U+1F1FA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NU.svg',
    country_uzb: 'Niue',
  },
  {
    country_rus: 'Новая Зеландия',
    country_eng: 'New Zealand',
    code: 'NZ',
    phone_code: 64,
    phone_mask: '(99) 999-9999',
    emoji: '🇳🇿',
    unicode: 'U+1F1F3 U+1F1FF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg',
    country_uzb: 'Yangi Zelandiya',
  },
  {
    country_rus: 'Новая Каледония',
    country_eng: 'New Caledonia',
    code: 'NC',
    phone_code: 687,
    phone_mask: '99.99.99',
    emoji: '🇳🇨',
    unicode: 'U+1F1F3 U+1F1E8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NC.svg',
    country_uzb: 'Yangi Kaledoniya',
  },
  {
    country_rus: 'Норвегия',
    country_eng: 'Norway',
    code: 'NO',
    phone_code: 47,
    phone_mask: '(999) 99-999',
    emoji: '🇳🇴',
    unicode: 'U+1F1F3 U+1F1F4',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg',
    country_uzb: 'Norvegiya',
  },
  {
    country_rus: 'Норфолк Айленд',
    country_eng: 'Norfolk Island',
    code: 'NF',
    phone_code: 672,
    phone_mask: '(9) 99999',
    emoji: '🇳🇫',
    unicode: 'U+1F1F3 U+1F1EB',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NF.svg',
    country_uzb: 'Norfolk oroli',
  },
  {
    country_rus: 'ОАЭ',
    country_eng: 'United Arab Emirates',
    code: 'AE',
    phone_code: 971,
    phone_mask: '(99) 999-9999',
    emoji: '🇦🇪',
    unicode: 'U+1F1E6 U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AE.svg',
    country_uzb: 'Birlashgan Arab Amirliklari',
  },
  {
    country_rus: 'Оман',
    country_eng: 'Oman',
    code: 'OM',
    phone_code: 968,
    phone_mask: '(9999) 9999',
    emoji: '🇴🇲',
    unicode: 'U+1F1F4 U+1F1F2',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/OM.svg',
    country_uzb: 'Ummon',
  },
  {
    country_rus: 'Остров Рождества',
    country_eng: 'Christmas Island',
    code: 'CX',
    phone_code: 672,
    phone_mask: '(999) 999-999',
    emoji: '🇨🇽',
    unicode: 'U+1F1E8 U+1F1FD',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CX.svg',
    country_uzb: 'Rojdestvo oroli',
  },
  {
    country_rus: 'Острова Кука',
    country_eng: 'Cook Islands',
    code: 'CK',
    phone_code: 682,
    phone_mask: '(99) 999',
    emoji: '🇨🇰',
    unicode: 'U+1F1E8 U+1F1F0',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CK.svg',
    country_uzb: 'Kuk orollari',
  },
  {
    country_rus: 'Острова Уоллис и Футуна',
    country_eng: 'Wallis and Futuna Islands',
    code: 'WF',
    phone_code: 681,
    phone_mask: '(99) 99-99',
    emoji: '🇼🇫',
    unicode: 'U+1F1FC U+1F1EB',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WF.svg',
    country_uzb: 'Uollis va Futuna orollari',
  },
  {
    country_rus: 'Пакистан',
    country_eng: 'Pakistan',
    code: 'PK',
    phone_code: 92,
    phone_mask: '(999) 9999999',
    emoji: '🇵🇰',
    unicode: 'U+1F1F5 U+1F1F0',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PK.svg',
    country_uzb: 'Pokiston',
  },
  {
    country_rus: 'Палау',
    country_eng: 'Palau',
    code: 'PW',
    phone_code: 680,
    phone_mask: '(999) 9999',
    emoji: '🇵🇼',
    unicode: 'U+1F1F5 U+1F1FC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PW.svg',
    country_uzb: 'Palau',
  },
  {
    country_rus: 'Панама',
    country_eng: 'Panama',
    code: 'PA',
    phone_code: 507,
    phone_mask: '(9999) 9999',
    emoji: '🇵🇦',
    unicode: 'U+1F1F5 U+1F1E6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PA.svg',
    country_uzb: 'Panama',
  },
  {
    country_rus: 'Папуа - Новая Гвинея',
    country_eng: 'Papua New Guinea',
    code: 'PG',
    phone_code: 675,
    phone_mask: '(9999) 9999',
    emoji: '🇵🇬',
    unicode: 'U+1F1F5 U+1F1EC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PG.svg',
    country_uzb: 'Papua Yangi Gvineya',
  },
  {
    country_rus: 'Парагвай',
    country_eng: 'Paraguay',
    code: 'PY',
    phone_code: 595,
    phone_mask: '(999) 999999',
    emoji: '🇵🇾',
    unicode: 'U+1F1F5 U+1F1FE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg',
    country_uzb: 'Paragvay',
  },
  {
    country_rus: 'Перу',
    country_eng: 'Peru',
    code: 'PE',
    phone_code: 51,
    phone_mask: '(999) 999-999',
    emoji: '🇵🇪',
    unicode: 'U+1F1F5 U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg',
    country_uzb: 'Peru',
  },
  {
    country_rus: 'Польша',
    country_eng: 'Poland',
    code: 'PL',
    phone_code: 48,
    phone_mask: '(999) 999-999',
    emoji: '🇵🇱',
    unicode: 'U+1F1F5 U+1F1F1',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg',
    country_uzb: 'Polsha',
  },
  {
    country_rus: 'Португалия',
    country_eng: 'Portugal',
    code: 'PT',
    phone_code: 351,
    phone_mask: '(999) 999-999',
    emoji: '🇵🇹',
    unicode: 'U+1F1F5 U+1F1F9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PT.svg',
    country_uzb: 'Portugaliya',
  },
  {
    country_rus: 'Пуэрто Рико',
    country_eng: 'Puerto Rico',
    code: 'PR',
    phone_code: 1787,
    phone_mask: '(999) 999-9999',
    emoji: '🇵🇷',
    unicode: 'U+1F1F5 U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PR.svg',
    country_uzb: 'Puerto-Riko',
  },
  {
    country_rus: 'Реюньон',
    country_eng: 'Reunion',
    code: 'RE',
    phone_code: 262,
    phone_mask: '(999) 99-99-99',
    emoji: '🇷🇪',
    unicode: 'U+1F1F7 U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RE.svg',
    country_uzb: 'Reyunion',
  },
  {
    country_rus: 'Россия',
    country_eng: 'Russian Federation',
    code: 'RU',
    phone_code: 7,
    phone_mask: '(999) 999-99-99',
    emoji: '🇷🇺',
    unicode: 'U+1F1F7 U+1F1FA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RU.svg',
    country_uzb: 'Rossiya',
  },
  {
    country_rus: 'Руанда',
    country_eng: 'Rwanda',
    code: 'RW',
    phone_code: 250,
    phone_mask: '(999) 999-999',
    emoji: '🇷🇼',
    unicode: 'U+1F1F7 U+1F1FC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RW.svg',
    country_uzb: 'Ruanda',
  },
  {
    country_rus: 'Румыния',
    country_eng: 'Romania',
    code: 'RO',
    phone_code: 40,
    phone_mask: '(999) 999-999',
    emoji: '🇷🇴',
    unicode: 'U+1F1F7 U+1F1F4',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg',
    country_uzb: 'Ruminiya',
  },
  {
    country_rus: 'США',
    country_eng: 'United States',
    code: 'US',
    phone_code: 1,
    phone_mask: '(999) 999-9999',
    emoji: '🇺🇸',
    unicode: 'U+1F1FA U+1F1F8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg',
    country_uzb: "Amerika Qo'shma Shtatlari",
  },
  {
    country_rus: 'Сальвадор',
    country_eng: 'El Salvador',
    code: 'SV',
    phone_code: 503,
    phone_mask: '(9999) 9999',
    emoji: '🇸🇻',
    unicode: 'U+1F1F8 U+1F1FB',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SV.svg',
    country_uzb: 'Salvador',
  },
  {
    country_rus: 'Самоа',
    country_eng: 'Samoa',
    code: 'WS',
    phone_code: 6,
    phone_mask: '999999',
    emoji: '🇼🇸',
    unicode: 'U+1F1FC U+1F1F8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WS.svg',
    country_uzb: 'Samoa',
  },
  {
    country_rus: 'Сан-Томе и Принсипи',
    country_eng: 'Sao Tome and Principe',
    code: 'ST',
    phone_code: 239,
    phone_mask: '(999) 9999',
    emoji: '🇸🇹',
    unicode: 'U+1F1F8 U+1F1F9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ST.svg',
    country_uzb: 'San-Tome va Prinsipi',
  },
  {
    country_rus: 'Саудовская Аравия',
    country_eng: 'Saudi Arabia',
    code: 'SA',
    phone_code: 966,
    phone_mask: '(99) 999-9999',
    emoji: '🇸🇦',
    unicode: 'U+1F1F8 U+1F1E6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SA.svg',
    country_uzb: 'Saudiya Arabistoni',
  },
  {
    country_rus: 'Свазиленд',
    country_eng: 'Swaziland',
    code: 'SZ',
    phone_code: 268,
    phone_mask: '(9999) 9999',
    emoji: '🇸🇿',
    unicode: 'U+1F1F8 U+1F1FF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SZ.svg',
    country_uzb: 'Svazilend',
  },
  {
    country_rus: 'Северная Корея',
    country_eng: 'Korea (North)',
    code: 'KP',
    phone_code: 850,
    phone_mask: '(999) 999-9999',
    emoji: '🇰🇵',
    unicode: 'U+1F1F0 U+1F1F5',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg',
    country_uzb: 'Shimoliy Koreya',
  },
  {
    country_rus: 'Северные Марианские острова',
    country_eng: 'Northern Mariana Islands',
    code: 'MP',
    phone_code: 670,
    phone_mask: '(999) 999-9999',
    emoji: '🇲🇵',
    unicode: 'U+1F1F2 U+1F1F5',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MP.svg',
    country_uzb: 'Shimoliy Mariana orollari',
  },
  {
    country_rus: 'Сейшельские о-ва',
    country_eng: 'Seychelles',
    code: 'SC',
    phone_code: 248,
    phone_mask: '(9) 999-999',
    emoji: '🇸🇨',
    unicode: 'U+1F1F8 U+1F1E8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SC.svg',
    country_uzb: 'Seyshel orollari',
  },
  {
    country_rus: 'Сен-Пьер и Микелон',
    country_eng: 'St. Pierre and Miquelon',
    code: 'PM',
    phone_code: 1784,
    phone_mask: '(99) 99-99',
    emoji: '🇵🇲',
    unicode: 'U+1F1F5 U+1F1F2',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PM.svg',
    country_uzb: 'Sen-Pyer va Mikelon',
  },
  {
    country_rus: 'Сенегал',
    country_eng: 'Senegal',
    code: 'SN',
    phone_code: 221,
    phone_mask: '(99) 999-99-99',
    emoji: '🇸🇳',
    unicode: 'U+1F1F8 U+1F1F3',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SN.svg',
    country_uzb: 'Senegal',
  },
  {
    country_rus: 'Сент-Китс и Невис',
    country_eng: 'Saint Kitts and Nevis',
    code: 'KN',
    phone_code: 1869,
    phone_mask: '(999) 999-9999',
    emoji: '🇰🇳',
    unicode: 'U+1F1F0 U+1F1F3',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KN.svg',
    country_uzb: 'Sent-Kits va Nevis',
  },
  {
    country_rus: 'Сент-Люсия',
    country_eng: 'Saint Lucia',
    code: 'LC',
    phone_code: 1758,
    phone_mask: '(999) 999-9999',
    emoji: '🇱🇨',
    unicode: 'U+1F1F1 U+1F1E8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LC.svg',
    country_uzb: 'Sent-Lyusiya',
  },
  {
    country_rus: 'Сербия',
    country_eng: 'Serbia',
    code: 'RS',
    phone_code: 381,
    phone_mask: '(99) 9999999',
    emoji: '🇷🇸',
    unicode: 'U+1F1F7 U+1F1F8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg',
    country_uzb: 'Serbiya',
  },
  {
    country_rus: 'Сингапур',
    country_eng: 'Singapore',
    code: 'SG',
    phone_code: 65,
    phone_mask: '(9999) 9999',
    emoji: '🇸🇬',
    unicode: 'U+1F1F8 U+1F1EC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg',
    country_uzb: 'Singapur',
  },
  {
    country_rus: 'Сирия',
    country_eng: 'Syria',
    code: 'SY',
    phone_code: 963,
    phone_mask: '(999) 999-999',
    emoji: '🇸🇾',
    unicode: 'U+1F1F8 U+1F1FE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SY.svg',
    country_uzb: 'Suriya',
  },
  {
    country_rus: 'Словакия',
    country_eng: 'Slovakia',
    code: 'SK',
    phone_code: 421,
    phone_mask: '(999) 999-999',
    emoji: '🇸🇰',
    unicode: 'U+1F1F8 U+1F1F0',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SK.svg',
    country_uzb: 'Slovakiya',
  },
  {
    country_rus: 'Словения',
    country_eng: 'Slovenia',
    code: 'SI',
    phone_code: 386,
    phone_mask: '(99) 999-999',
    emoji: '🇸🇮',
    unicode: 'U+1F1F8 U+1F1EE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg',
    country_uzb: 'Sloveniya',
  },
  {
    country_rus: 'Соломоновы острова',
    country_eng: 'Solomon Islands',
    code: 'SB',
    phone_code: 677,
    phone_mask: '(99) 99999',
    emoji: '🇸🇧',
    unicode: 'U+1F1F8 U+1F1E7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SB.svg',
    country_uzb: 'Solomon orollari',
  },
  {
    country_rus: 'Сомали',
    country_eng: 'Somalia',
    code: 'SO',
    phone_code: 252,
    phone_mask: '(9) 9999999',
    emoji: '🇸🇴',
    unicode: 'U+1F1F8 U+1F1F4',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SO.svg',
    country_uzb: 'Somali',
  },
  {
    country_rus: 'Судан',
    country_eng: 'Sudan',
    code: 'SD',
    phone_code: 249,
    phone_mask: '(99) 999-9999',
    emoji: '🇸🇩',
    unicode: 'U+1F1F8 U+1F1E9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SD.svg',
    country_uzb: 'Sudan',
  },
  {
    country_rus: 'Суринам',
    country_eng: 'Suriname',
    code: 'SR',
    phone_code: 597,
    phone_mask: '(999) 9999',
    emoji: '🇸🇷',
    unicode: 'U+1F1F8 U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SR.svg',
    country_uzb: 'Surinam',
  },
  {
    country_rus: 'Сьерра-Леоне',
    country_eng: 'Sierra Leone',
    code: 'SL',
    phone_code: 232,
    phone_mask: '(99) 999999',
    emoji: '🇸🇱',
    unicode: 'U+1F1F8 U+1F1F1',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SL.svg',
    country_uzb: 'Syerra-Leone',
  },
  {
    country_rus: 'Таджикистан',
    country_eng: 'Tajikistan',
    code: 'TJ',
    phone_code: 992,
    phone_mask: '(999) 99-9999',
    emoji: '🇹🇯',
    unicode: 'U+1F1F9 U+1F1EF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TJ.svg',
    country_uzb: 'Tojikiston',
  },
  {
    country_rus: 'Таиланд',
    country_eng: 'Thailand',
    code: 'TH',
    phone_code: 66,
    phone_mask: '(99) 999-9999',
    emoji: '🇹🇭',
    unicode: 'U+1F1F9 U+1F1ED',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg',
    country_uzb: 'Tailand',
  },
  {
    country_rus: 'Тайвань',
    country_eng: 'Taiwan',
    code: 'TW',
    phone_code: 886,
    phone_mask: '(999) 999-999',
    emoji: '🇹🇼',
    unicode: 'U+1F1F9 U+1F1FC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg',
    country_uzb: 'Tayvan',
  },
  {
    country_rus: 'Танзания',
    country_eng: 'Tanzania',
    code: 'TZ',
    phone_code: 255,
    phone_mask: '(999) 999-999',
    emoji: '🇹🇿',
    unicode: 'U+1F1F9 U+1F1FF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TZ.svg',
    country_uzb: 'Tanzaniya',
  },
  {
    country_rus: 'Теркс и Кайкос',
    country_eng: 'Turks and Caicos Islands',
    code: 'TC',
    phone_code: 1649,
    phone_mask: '(999) 999-9999',
    emoji: '🇹🇨',
    unicode: 'U+1F1F9 U+1F1E8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TC.svg',
    country_uzb: 'Turks va Kaykos orollari',
  },
  {
    country_rus: 'Того',
    country_eng: 'Togo',
    code: 'TG',
    phone_code: 228,
    phone_mask: '(99) 99-99-99',
    emoji: '🇹🇬',
    unicode: 'U+1F1F9 U+1F1EC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TG.svg',
    country_uzb: 'Togo',
  },
  {
    country_rus: 'Тонга',
    country_eng: 'Tonga',
    code: 'TO',
    phone_code: 676,
    phone_mask: '(999) 9999',
    emoji: '🇹🇴',
    unicode: 'U+1F1F9 U+1F1F4',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TO.svg',
    country_uzb: 'Tonga',
  },
  {
    country_rus: 'Тринидад и Тобаго',
    country_eng: 'Trinidad And Tobago',
    code: 'TT',
    phone_code: 1868,
    phone_mask: '(999) 999-9999',
    emoji: '🇹🇹',
    unicode: 'U+1F1F9 U+1F1F9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TT.svg',
    country_uzb: 'Trinidad va Tobago',
  },
  {
    country_rus: 'Тувалу',
    country_eng: 'Tuvalu',
    code: 'TV',
    phone_code: 688,
    phone_mask: '999999',
    emoji: '🇹🇻',
    unicode: 'U+1F1F9 U+1F1FB',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TV.svg',
    country_uzb: 'Tuvalu',
  },
  {
    country_rus: 'Тунис',
    country_eng: 'Tunisia',
    code: 'TN',
    phone_code: 21,
    phone_mask: '(99) 999-999',
    emoji: '🇹🇳',
    unicode: 'U+1F1F9 U+1F1F3',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TN.svg',
    country_uzb: 'Tunis',
  },
  {
    country_rus: 'Туркменистан',
    country_eng: 'Turkmenistan',
    code: 'TM',
    phone_code: 993,
    phone_mask: '(99) 999999',
    emoji: '🇹🇲',
    unicode: 'U+1F1F9 U+1F1F2',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TM.svg',
    country_uzb: 'Turkmaniston',
  },
  {
    country_rus: 'Турция',
    country_eng: 'Turkey',
    code: 'TR',
    phone_code: 90,
    phone_mask: '(999) 999-99-99',
    emoji: '🇹🇷',
    unicode: 'U+1F1F9 U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg',
    country_uzb: 'Turkiya',
  },
  {
    country_rus: 'Уганда',
    country_eng: 'Uganda',
    code: 'UG',
    phone_code: 256,
    phone_mask: '(999) 999999',
    emoji: '🇺🇬',
    unicode: 'U+1F1FA U+1F1EC',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UG.svg',
    country_uzb: 'Uganda',
  },
  {
    country_rus: 'Узбекистан',
    country_eng: 'Uzbekistan',
    code: 'UZ',
    phone_code: 998,
    phone_mask: '(99) 999-99-99',
    emoji: '🇺🇿',
    unicode: 'U+1F1FA U+1F1FF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UZ.svg',
    country_uzb: "O'zbekiston",
  },
  {
    country_rus: 'Украина',
    country_eng: 'Ukraine',
    code: 'UA',
    phone_code: 380,
    phone_mask: '(99) 999-9999',
    emoji: '🇺🇦',
    unicode: 'U+1F1FA U+1F1E6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg',
    country_uzb: 'Ukraina',
  },
  {
    country_rus: 'Уругвай',
    country_eng: 'Uruguay',
    code: 'UY',
    phone_code: 598,
    phone_mask: '(99) 999-999',
    emoji: '🇺🇾',
    unicode: 'U+1F1FA U+1F1FE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UY.svg',
    country_uzb: 'Urugvay',
  },
  {
    country_rus: 'Фарерские острова',
    country_eng: 'Faroe Islands',
    code: 'FO',
    phone_code: 298,
    phone_mask: '999999',
    emoji: '🇫🇴',
    unicode: 'U+1F1EB U+1F1F4',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FO.svg',
    country_uzb: 'Farer orollari',
  },
  {
    country_rus: 'Фиджи',
    country_eng: 'Fiji',
    code: 'FJ',
    phone_code: 679,
    phone_mask: '(999) 9999',
    emoji: '🇫🇯',
    unicode: 'U+1F1EB U+1F1EF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FJ.svg',
    country_uzb: 'Fiji',
  },
  {
    country_rus: 'Филиппины',
    country_eng: 'Philippines',
    code: 'PH',
    phone_code: 63,
    phone_mask: '(999) 999-9999',
    emoji: '🇵🇭',
    unicode: 'U+1F1F5 U+1F1ED',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg',
    country_uzb: 'Filippin',
  },
  {
    country_rus: 'Финляндия',
    country_eng: 'Finland',
    code: 'FI',
    phone_code: 358,
    phone_mask: '(99) 9999999',
    emoji: '🇫🇮',
    unicode: 'U+1F1EB U+1F1EE',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FI.svg',
    country_uzb: 'Finlandiya',
  },
  {
    country_rus: 'Фоклендские острова',
    country_eng: 'Falkland Islands',
    code: 'FK',
    phone_code: 500,
    phone_mask: '99999',
    emoji: '🇫🇰',
    unicode: 'U+1F1EB U+1F1F0',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FK.svg',
    country_uzb: 'Folklend orollari',
  },
  {
    country_rus: 'Франция',
    country_eng: 'France',
    code: 'FR',
    phone_code: 33,
    phone_mask: '(9) 99-99-99-99',
    emoji: '🇫🇷',
    unicode: 'U+1F1EB U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg',
    country_uzb: 'Fransiya',
  },
  {
    country_rus: 'Французская Гвиана',
    country_eng: 'French Guiana',
    code: 'GF',
    phone_code: 594,
    phone_mask: '(999) 99-99-99',
    emoji: '🇬🇫',
    unicode: 'U+1F1EC U+1F1EB',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GF.svg',
    country_uzb: 'Fransuz Gvianasi',
  },
  {
    country_rus: 'Французская Полинезия',
    country_eng: 'French Polynesia',
    code: 'PF',
    phone_code: 689,
    phone_mask: '(99) 99-99-99',
    emoji: '🇵🇫',
    unicode: 'U+1F1F5 U+1F1EB',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PF.svg',
    country_uzb: 'Fransuz Polineziyasi',
  },
  {
    country_rus: 'Хорватия',
    country_eng: 'Croatia',
    code: 'HR',
    phone_code: 385,
    phone_mask: '(99) 999-9999',
    emoji: '🇭🇷',
    unicode: 'U+1F1ED U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HR.svg',
    country_uzb: 'Xorvatiya',
  },
  {
    country_rus: 'Центральноафриканская Республика',
    country_eng: 'Central African Republic',
    code: 'CF',
    phone_code: 236,
    phone_mask: '(99) 99-99-99',
    emoji: '🇨🇫',
    unicode: 'U+1F1E8 U+1F1EB',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CF.svg',
    country_uzb: 'Markaziy Afrika Respublikasi',
  },
  {
    country_rus: 'Чад',
    country_eng: 'Chad',
    code: 'TD',
    phone_code: 235,
    phone_mask: '(99) 99-99-99',
    emoji: '🇹🇩',
    unicode: 'U+1F1F9 U+1F1E9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TD.svg',
    country_uzb: 'Chad',
  },
  {
    country_rus: 'Черногория',
    country_eng: 'Montenegro',
    code: 'ME',
    phone_code: 382,
    phone_mask: '(99) 999-999',
    emoji: '🇲🇪',
    unicode: 'U+1F1F2 U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ME.svg',
    country_uzb: 'Chernogoriya',
  },
  {
    country_rus: 'Чехия',
    country_eng: 'Czech Republic',
    code: 'CZ',
    phone_code: 420,
    phone_mask: '(999) 999-999',
    emoji: '🇨🇿',
    unicode: 'U+1F1E8 U+1F1FF',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CZ.svg',
    country_uzb: 'Chexiya',
  },
  {
    country_rus: 'Чили',
    country_eng: 'Chile',
    code: 'CL',
    phone_code: 56,
    phone_mask: '(9) 9999-9999',
    emoji: '🇨🇱',
    unicode: 'U+1F1E8 U+1F1F1',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CL.svg',
    country_uzb: 'Chili',
  },
  {
    country_rus: 'Швейцария',
    country_eng: 'Switzerland',
    code: 'CH',
    phone_code: 41,
    phone_mask: '(99) 999-99-99',
    emoji: '🇨🇭',
    unicode: 'U+1F1E8 U+1F1ED',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CH.svg',
    country_uzb: 'Shveysariya',
  },
  {
    country_rus: 'Швеция',
    country_eng: 'Sweden',
    code: 'SE',
    phone_code: 46,
    phone_mask: '(99) 999-99-99',
    emoji: '🇸🇪',
    unicode: 'U+1F1F8 U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg',
    country_uzb: 'Shvetsiya',
  },
  {
    country_rus: 'Шри-Ланка',
    country_eng: 'Sri Lanka',
    code: 'LK',
    phone_code: 94,
    phone_mask: '(99) 999-9999',
    emoji: '🇱🇰',
    unicode: 'U+1F1F1 U+1F1F0',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LK.svg',
    country_uzb: 'Shri-Lanka',
  },
  {
    country_rus: 'Эквадор',
    country_eng: 'Ecuador',
    code: 'EC',
    phone_code: 593,
    phone_mask: '(99) 999-9999',
    emoji: '🇪🇨',
    unicode: 'U+1F1EA U+1F1E8',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EC.svg',
    country_uzb: 'Ekvador',
  },
  {
    country_rus: 'Экваториальная Гвинея',
    country_eng: 'Equatorial Guinea',
    code: 'GQ',
    phone_code: 240,
    phone_mask: '(999) 999-999',
    emoji: '🇬🇶',
    unicode: 'U+1F1EC U+1F1F6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GQ.svg',
    country_uzb: 'Ekvatorial Gvineya',
  },
  {
    country_rus: 'Эритрея',
    country_eng: 'Eritrea',
    code: 'ER',
    phone_code: 291,
    phone_mask: '(9) 999-999',
    emoji: '🇪🇷',
    unicode: 'U+1F1EA U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ER.svg',
    country_uzb: 'Eritreya',
  },
  {
    country_rus: 'Эстония',
    country_eng: 'Estonia',
    code: 'EE',
    phone_code: 372,
    phone_mask: '(9999) 9999',
    emoji: '🇪🇪',
    unicode: 'U+1F1EA U+1F1EA',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EE.svg',
    country_uzb: 'Estoniya',
  },
  {
    country_rus: 'Эфиопия',
    country_eng: 'Ethiopia',
    code: 'ET',
    phone_code: 251,
    phone_mask: '(99) 999-9999',
    emoji: '🇪🇹',
    unicode: 'U+1F1EA U+1F1F9',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ET.svg',
    country_uzb: 'Efiopiya',
  },
  {
    country_rus: 'ЮАР',
    country_eng: 'South Africa',
    code: 'ZA',
    phone_code: 27,
    phone_mask: '(99) 999-9999',
    emoji: '🇿🇦',
    unicode: 'U+1F1FF U+1F1E6',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg',
    country_uzb: 'Janubiy Afrika Respublikasi',
  },
  {
    country_rus: 'Южная Корея',
    country_eng: 'Korea (South)',
    code: 'KR',
    phone_code: 82,
    phone_mask: '(99) 9999-9999',
    emoji: '🇰🇷',
    unicode: 'U+1F1F0 U+1F1F7',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg',
    country_uzb: 'Janubiy Koreya',
  },
  {
    country_rus: 'Ямайка',
    country_eng: 'Jamaica',
    code: 'JM',
    phone_code: 1876,
    phone_mask: '(999) 999-9999',
    emoji: '🇯🇲',
    unicode: 'U+1F1EF U+1F1F2',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JM.svg',
    country_uzb: 'Yamayka',
  },
  {
    country_rus: 'Япония',
    country_eng: 'Japan',
    code: 'JP',
    phone_code: 81,
    phone_mask: '(99) 9999-9999',
    emoji: '🇯🇵',
    unicode: 'U+1F1EF U+1F1F5',
    image: 'https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg',
    country_uzb: 'Yaponiya',
  },
] as ICountry[]
